#to get the instance of Travis CI
sudo: required
dist: trusty

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

branches:
  only:
    - master
    - e2eTests

#
# Build Lifecycle:
#

before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic
  - cd restoMobile
  - ionic state clear

install: npm install

# that's how travis run on chrome
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script:
  - npm run test-ci  # unit tests
  - npm run e2e      # run e2e tests against ionic
