swagger: "2.0"
info:
  version: "0.0.1"
  title: RestoTouch
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /restaurant:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurant
    get:
      description: Returns the list of restaurants
      # used as the method name of the controller
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RestaurantListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: save
      description: Add a restaurant
      # movie info to be stored
      parameters:
        - name: restaurant
          description: Restaurant properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Restaurant"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /restaurant/{name}:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurant
    get:
      description: Returns a specific restaurant
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: name
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Restaurant"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates a restaurant
      # used as the method name of the controller
      operationId: update
      parameters:
        - name: name
          type: string
          in: path
          required: true
        - name: restaurant
          description: Restaurant properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Restaurant"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a restaurant
      # used as the method name of the controller
      operationId: del
      parameters:
        - name: name
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /register:
    x-swagger-router-controller: account
    post:
      operationId: register
      description: Register a new user
      # movie info to be stored
      parameters:
        - name: user
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    x-swagger-router-controller: account
    post:
      operationId: login
      description: Authenticate an existing user

      parameters:
        - name: auth
          description: User credentials
          in: body
          required: true
          schema:
            $ref: "#/definitions/Auth"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
    required:
      - firstName
      - lastName
      - email
  Auth:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
        - email
        - password
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
    required:
      - success
      - description
  RestaurantListResponse:
    required:
      - restaurants
    properties:
      # The array of movies
      restaurants:
        type: array
        items:
          "$ref": "#/definitions/Restaurant"
  Language:
    type: object
    properties:
      code:
        type: string
  RestaurantTranslations:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
    required:
      - name
      - description
  Restaurant:
    type: object
    properties:
      address:
        type: string
      mOpen:
        type: string
      mClose:
        type: string
      tuOpen:
        type: string
      tuClose:
        type: string
      wOpen:
        type: string
      wClose:
        type: string
      thOpen:
        type: string
      thClose:
        type: string
      fOpen:
        type: string
      fClose:
        type: string
      saOpen:
        type: string
      saClose:
        type: string
      suOpen:
        type: string
      suClose:
        type: string
      supportedLanguages:
        type: array
        items:
          "$ref": "#/definitions/Language"
      translations:
        type: array
        items:
          "$ref": "#/definitions/RestaurantTranslations"
    required:
      - address
      - mOpen
      - mClose
      - tuOpen
      - tuClose
      - wOpen
      - wClose
      - thOpen
      - thClose
      - fOpen
      - fClose
      - saOpen
      - saClose
      - suOpen
      - suClose
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
