swagger: "2.0"
info:
  version: "0.0.1"
  title: RestoTouch
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  # -----------------------------------------/// Category ///
  /category:
     # binds a127 app logic to a route
    x-swagger-router-controller: category
    get:
      # used as the method name of the controller
      operationId: getAllCategories
      description: Returns the list of categories
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CategoriesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: addCategory
      description: Add a category
      parameters:
        - name: category
          description: category properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /category/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: category
    get:
      description: Returns a specific category
      # used as the method name of the controller
      operationId: getCategory
      parameters:
        - name: id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Category"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates a category
      # used as the method name of the controller
      operationId: updateCategory
      parameters:
        - name: id
          type: number
          in: path
          required: true
        - name: category
          description: Category properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a category
      # used as the method name of the controller
      operationId: deleteCategory
      parameters:
        - name: id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  # -----------------------------------------/// Restaurant ///
  /restaurant:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurant
    get:
      description: Returns the list of restaurants
      # used as the method name of the controller
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RestaurantListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: save
      description: Add a restaurant
      # movie info to be stored
      parameters:
        - name: restaurant
          description: Restaurant properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Restaurant"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /restaurant/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurant
    get:
      description: Returns a specific restaurant
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Restaurant"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates a restaurant
      # used as the method name of the controller
      operationId: update
      parameters:
        - name: id
          type: number
          in: path
          required: true
        - name: restaurant
          description: Restaurant properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Restaurant"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a restaurant
      # used as the method name of the controller
      operationId: del
      parameters:
        - name: id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /menu:
    # binds a127 app logic to a route
    x-swagger-router-controller: menu
    get:
      description: Returns the list of menus
      # used as the method name of the controller
      operationId: getAllMenu
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MenuListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: saveMenu
      description: Add a menu
      # menu info to be stored
      parameters:
        - name: restaurant
          description: Menu properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Menu"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /menu/{name}:
    # binds a127 app logic to a route
    x-swagger-router-controller: menu
    get:
      description: Returns a specific menu
      # used as the method name of the controller
      operationId: getMenu
      parameters:
        - name: name
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Menu"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates a menu
      # used as the method name of the controller
      operationId: updateMenu
      parameters:
        - name: name
          type: string
          in: path
          required: true
        - name: menu
          description: Menu properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Menu"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a menu
      # used as the method name of the controller
      operationId: delMenu
      parameters:
        - name: name
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /restaurantmenu:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurantmenu
    post:
      operationId: saveRestaurantMenu
      description: Add a restaurant menu
      # menu info to be stored
      parameters:
        - name: restaurantmenu
          description: Restaurant Menu relation
          in: body
          required: true
          schema:
            $ref: "#/definitions/RestaurantMenu"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /restaurantmenu/{restaurantId}{menuId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: restaurantmenu
    delete:
      description: Deletes a Restaurant Menu relation
      # used as the method name of the controller
      operationId: delRestaurantMenu
      parameters:
        - name: restaurantId
          description: Restaurant Id
          type: number
          in: path
          required: true
        - name: menuId
          description: Menu Id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /menucategory:
    # binds a127 app logic to a route
    x-swagger-router-controller: menucategory
    post:
      operationId: saveMenuCategory
      description: Add a category to menu
      # menu info to be stored
      parameters:
        - name: menucategory
          description: Menu Category relation
          in: body
          required: true
          schema:
            $ref: "#/definitions/MenuCategory"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /menucategory/{menuId}{categoryId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: menucategory
    delete:
      description: Deletes a Category in Menu
      # used as the method name of the controller
      operationId: delMenuCategory
      parameters:
        - name: menuId
          description: a Category Id
          type: number
          in: path
          required: true
        - name: categoryId
          description: a Menu Id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  # -----------------------------------------/// Register ///
  /register:
    x-swagger-router-controller: account
    post:
      operationId: register
      description: Register a new user
      # movie info to be stored
      parameters:
        - name: user
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  # -----------------------------------------/// Login ///
  /login:
    x-swagger-router-controller: account
    post:
      operationId: login
      description: Authenticate an existing user

      parameters:
        - name: auth
          description: User credentials
          in: body
          required: true
          schema:
            $ref: "#/definitions/Auth"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
    required:
      - firstName
      - lastName
      - email
  Auth:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
        - email
        - password
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
    required:
      - success
      - description
  CategoriesResponse:
    required:
      - categories
    properties:
      # Array of category
      categories:
        type: array
        items:
          "$ref": "#/definitions/Category"
  Category:
    type: object
    properties:
      categoryName:
        type: string
    required:
      - categoryName
  RestaurantListResponse:
    required:
      - restaurants
    properties:
      # The array of restaurants
      restaurants:
        type: array
        items:
          "$ref": "#/definitions/Restaurant"
  Language:
    type: object
    properties:
      code:
        type: string
  RestaurantTranslations:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      languageCode:
        type: string
    required:
      - name
      - description
      - languageCode
  Restaurant:
    type: object
    properties:
      address:
        type: string
      mOpen:
        type: string
      mClose:
        type: string
      tuOpen:
        type: string
      tuClose:
        type: string
      wOpen:
        type: string
      wClose:
        type: string
      thOpen:
        type: string
      thClose:
        type: string
      fOpen:
        type: string
      fClose:
        type: string
      saOpen:
        type: string
      saClose:
        type: string
      suOpen:
        type: string
      suClose:
        type: string
      supportedLanguages:
        type: array
        items:
          "$ref": "#/definitions/Language"
      translations:
        type: array
        items:
          "$ref": "#/definitions/RestaurantTranslations"
    required:
      - address
      - mOpen
      - mClose
      - tuOpen
      - tuClose
      - wOpen
      - wClose
      - thOpen
      - thClose
      - fOpen
      - fClose
      - saOpen
      - saClose
      - suOpen
      - suClose
  MenuListResponse:
    required:
      - menus
    properties:
      # The array of menus
      menus:
        type: array
        items:
          "$ref": "#/definitions/Menu"
  Menu:
    type: object
    properties:
      name:
        type: string
    required:
      - name
  RestaurantMenu:
    type: object
    properties:
      RestaurantId:
        type: number
      MenuId:
        type: number
    required:
      - RestaurantId
      - MenuId
  MenuCategory:
    type: object
    properties:
      MenuId:
        type: number
      CategoryId:
        type: number
    required:
      - MenuId
      - CategoryId
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
